// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/assessments/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assessments/[id].delete').default>>>>
    }
    '/api/assessments/:id/pdf': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assessments/[id]/pdf.get').default>>>>
    }
    '/api/assessments/export-zip': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assessments/export-zip.post').default>>>>
    }
    '/api/assessments': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assessments/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/assessments/index.post').default>>>>
    }
    '/api/students': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/students/index.post').default>>>>
    }
    '/api/supervisors': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/supervisors/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/supervisors/index.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}