// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/5/2025, 8:29:12 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/USER/Desktop/madziwa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/madziwa/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/madziwa/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/madziwa/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/madziwa/plugins/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/madziwa/composables/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/madziwa/utils/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/madziwa/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/madziwa/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/madziwa/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/madziwa/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;